database:
  name: 'jarvis'
  user: '2bw9XzdKWiSnJgo.root'
  password: 'GAVkkA9tDiGEtV0Q'
  host: 'gateway01.ap-southeast-1.prod.aws.tidbcloud.com'
  port: 4000
  ssl:
    ca: '/etc/ssl/cert.pem' 
    ssl_model: 'VERIFY_IDENTITY'

gpt:
  model: 'GPT_4'

logging:
  level: 'INFO'

assistant:
  timeout: 1
  verbose: true
  continuous: true

